import axios from "axios";
import Head from "next/head";
import BMC from "../../components/bmc";
import Footer from "../../components/Footer";
import ScrollTopArrow from "../../components/Scroll";

import styles from "../../styles/Post.module.css";

const Posts = (props) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>আর্থিক | {props.post.title} </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
          <img
            src="https://images.unsplash.com/photo-1533422902779-aff35862e462?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80"
            alt="First slide"
          />
        </header>
        <main className={styles.main}>
          <BMC />
          <ScrollTopArrow />
          <h1>{props.post.title}</h1>
          <p>{props.post.body}</p>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Posts;

export async function getServerSideProps(context) {
  const id = context.params.id;
  const response = await axios.get(
    "https://jsonplaceholder.typicode.com/posts/" + id
  );
  return {
    props: {
      post: response.data,
    },
  };
}
