import Head from "next/head";
import CardSection from "../components/CardSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Latest from "../components/Latest";
import BMC from "../components/bmc";

import axios from "axios";

import styles from "../styles/Home.module.css";
import ScrollTopArrow from "../components/Scroll";

export default function Home(props) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>আর্থিক</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.main}>
          <BMC />
          <ScrollTopArrow />
          <Latest posts={props.latest} />
          <CardSection posts={props.posts} />
        </main>
        <Footer />
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const response = await axios.get(
    "https://jsonplaceholder.typicode.com/posts"
  );
  const data = response.data;
  const latest = [
    data[data.length - 1],
    data[data.length - 2],
    data[data.length - 3],
  ];
  return {
    props: {
      posts: data,
      latest,
    },
  };
}
